// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOd3A5PYBfuFRiHF8M7A6U8UfWpQWTCE4',
    appId: '1:766228351603:android:6c227487e8a84a9349b806',
    messagingSenderId: '766228351603',
    projectId: 'travel-guide-f6973',
    storageBucket: 'travel-guide-f6973.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA3nssSsPcKMhHklzQYlcaHC_eDQQj8aE',
    appId: '1:766228351603:ios:1f106ffdac74b53a49b806',
    messagingSenderId: '766228351603',
    projectId: 'travel-guide-f6973',
    storageBucket: 'travel-guide-f6973.firebasestorage.app',
    iosClientId:
        '766228351603-kinlo2t2oov4tl1f9msd6djmikperut5.apps.googleusercontent.com',
    iosBundleId: 'com.codenour.travel-guide',
  );
}
